version: "3.8"

services:
  influxdb:
    image: influxdb:1.8
    container_name: k6-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6_load_tests
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6password
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - k6-monitoring
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/k6-dashboard.json
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_UID=k6-dashboard
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-k6-dashboard.json:/etc/grafana/provisioning/dashboards/k6-dashboard.json
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/influxdb.yml
    networks:
      - k6-monitoring
    depends_on:
      influxdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: K6 test runner container
  k6-runner:
    image: grafana/k6:latest
    container_name: k6-test-runner
    volumes:
      - .:/scripts
      - ./test-results:/test-results
    working_dir: /scripts
    networks:
      - k6-monitoring
    depends_on:
      influxdb:
        condition: service_healthy
    profiles:
      - testing
    command: >
      sh -c "
        echo 'Waiting for InfluxDB to be ready...' &&
        sleep 10 &&
        echo 'Running K6 test with InfluxDB output...' &&
        k6 run --out influxdb=http://influxdb:8086/k6_load_tests k6_api_load_test.js
      "

volumes:
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local
  grafana-data:
    driver: local

networks:
  k6-monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
